<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Dashboard\**" />
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Interfaces\Dashboard\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Interfaces\Dashboard\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Actors\" />
    <Folder Include="DTOs\Processes\OutSide\" />
    <Folder Include="IServices\Actors\" />
    <Folder Include="IServices\Processes\OutSide\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataWarehouse.Domain\DataWarehouse.Domain.csproj" />
  </ItemGroup>

</Project>
