using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataWarehouse.Domain.Entities.Actors
{
    public class WarehouseItem
    {
        public int WarehouseItemId { get; set; }

        public int ItemId { get; set; }
        public Item Item { get; set; }

        public int WarehouseId { get; set; }
        public Warehouse Warehouse { get; set; }
        public string ItemCode { get; set; }
        public string WarehouseCode { get; set; }
        public double? InStock { get; set; }
        public double? MinStock { get; set; }
        public bool FinishedGood { get; set; }

        public bool HasActiveBOM { get; set; }

       // public string IsAutoGenerated { get; set; } = "BackFlush";  // not found Manual / BackFlush

        // An item added in batches, not as a full quantity.
        public bool IsBatchManaged { get; set; } = true;
        public bool IsActive { get; set; } = true;

    }
}
