using System.ComponentModel.DataAnnotations;

namespace DataWarehouse.Core.DTOs.Processes.BulkProductions;

public class FinishedGoodItemDTO
{
    public int? FinishedGoodItemId { get; set; }

    public bool HasActiveBOM { get; set; }

    [Required(ErrorMessage = "Item ID is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Item ID must be greater than 0")]
    public int ItemId { get; set; }

    [Required(ErrorMessage = "Warehouse ID is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Warehouse ID must be greater than 0")]
    public int WarehouseId { get; set; }
}

public class FinishedGoodItemResponseDTO
{
    public int FinishedGoodItemId { get; set; }
    public bool HasActiveBOM { get; set; }
    public string IsAutoGenerated { get; set; }
    public bool IsBatchManaged { get; set; }
    public bool IsActive { get; set; }
    public int ItemId { get; set; }
    public string? ItemName { get; set; }
    public string? ItemCode { get; set; }
    public int WarehouseId { get; set; }
    public string? WarehouseName { get; set; }
    public string? WarehouseCode { get; set; }
}

