using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataWarehouse.Domain.Enums
{
    public enum PurchaseStatus
    {
        Draft = 1, Processing = 2, Approval = 3 , Rejected = 4 , Completed = 5, PartiallyFailed = 6

    }
    public enum PurchaseIsAutoGeneratedStatus
    {
        Manual = 1, BackFlush = 2
    }


    public enum PurchaseItemStatus
    {
        Draft = 1, Planned = 2, Released = 3, Received = 4, Closed = 5, Failed = 6
    }
}
